# qrs
# Copyright (c) 2022-present NAVER Corp.
# Creative Commons Attribution-NonCommercial-ShareAlike 4.0 license

sampler:
  class: "DirectSampler"
proposal:
  class: "lm.HFAutoregressiveLM"
  args:
    model_name: "gpt2"
    prompt: "This is Wikileaks:"
