python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/female_science/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/female_science/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/female_science/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/female_science/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/female_science/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/female_science/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/female_science/qrs-female_science-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/female_science/qrs-female_science-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/female_science/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/female_science/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/female_science/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/female_science/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/female_science/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/female_science/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/female_science/qrs-female_science-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/female_science/qrs-female_science-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/female_science/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/female_science/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/female_science/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/female_science/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/female_science/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/female_science/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/female_science/qrs-female_science-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/female_science/qrs-female_science-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/female_science/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/female_science/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/female_science/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/female_science/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/female_science/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/female_science/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/female_science/qrs-female_science-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/female_science/qrs-female_science-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/female_science/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/female_science/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/female_science/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/female_science/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/female_science/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/female_science/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/female_science/qrs-female_science-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/female_science/qrs-female_science-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/female_science/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/female_science/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/female_science/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/female_science/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/female_science/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/female_science/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/female_science/qrs-female_science-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/female_science/qrs-female_science-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/female_science/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/female_science/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/female_science/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/female_science/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/female_science/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/female_science/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/female_science/qrs-female_science-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/female_science/qrs-female_science-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/female_science/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/female_science/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/female_science/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/female_science/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/female_science/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/female_science/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/female_science/qrs-female_science-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/female_science/qrs-female_science-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/female_science/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/female_science/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/female_science/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/female_science/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/female_science/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/female_science/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/female_science/qrs-female_science-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/female_science/qrs-female_science-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/female_science/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/female_science/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/female_science/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/female_science/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/female_science/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/female_science/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/female_science/qrs-female_science-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/female_science/qrs-female_science-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/amazing/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/amazing/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/amazing/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/amazing/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/amazing/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/amazing/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/amazing/qrs-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/amazing/qrs-amazing-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/amazing/rwmh-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/amazing/rwmh-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/amazing/rwmhreset-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/amazing/rwmhreset-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/amazing/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/amazing/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/amazing/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/amazing/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/amazing/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/amazing/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/amazing/qrs-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/amazing/qrs-amazing-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/amazing/rwmh-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/amazing/rwmh-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/amazing/rwmhreset-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/amazing/rwmhreset-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/amazing/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/amazing/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/amazing/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/amazing/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/amazing/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/amazing/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/amazing/qrs-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/amazing/qrs-amazing-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/amazing/rwmh-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/amazing/rwmh-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/amazing/rwmhreset-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/amazing/rwmhreset-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/amazing/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/amazing/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/amazing/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/amazing/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/amazing/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/amazing/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/amazing/qrs-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/amazing/qrs-amazing-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/amazing/rwmh-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/amazing/rwmh-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/amazing/rwmhreset-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/amazing/rwmhreset-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/amazing/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/amazing/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/amazing/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/amazing/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/amazing/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/amazing/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/amazing/qrs-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/amazing/qrs-amazing-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/amazing/rwmh-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/amazing/rwmh-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/amazing/rwmhreset-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/amazing/rwmhreset-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/amazing/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/amazing/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/amazing/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/amazing/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/amazing/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/amazing/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/amazing/qrs-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/amazing/qrs-amazing-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/amazing/rwmh-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/amazing/rwmh-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/amazing/rwmhreset-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/amazing/rwmhreset-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/amazing/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/amazing/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/amazing/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/amazing/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/amazing/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/amazing/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/amazing/qrs-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/amazing/qrs-amazing-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/amazing/rwmh-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/amazing/rwmh-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/amazing/rwmhreset-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/amazing/rwmhreset-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/amazing/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/amazing/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/amazing/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/amazing/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/amazing/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/amazing/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/amazing/qrs-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/amazing/qrs-amazing-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/amazing/rwmh-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/amazing/rwmh-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/amazing/rwmhreset-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/amazing/rwmhreset-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/amazing/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/amazing/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/amazing/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/amazing/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/amazing/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/amazing/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/amazing/qrs-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/amazing/qrs-amazing-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/amazing/rwmh-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/amazing/rwmh-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/amazing/rwmhreset-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/amazing/rwmhreset-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/amazing/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/amazing/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/amazing/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/amazing/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/amazing/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/amazing/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/amazing/qrs-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/amazing/qrs-amazing-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/amazing/rwmh-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/amazing/rwmh-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/amazing/rwmhreset-0.001-amazing-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/amazing/rwmhreset-0.001-amazing-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/wikileaks/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/wikileaks/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/wikileaks/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/wikileaks/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/wikileaks/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/wikileaks/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/wikileaks/qrs-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/wikileaks/qrs-wikileaks-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/wikileaks/rwmh-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/wikileaks/rwmh-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/wikileaks/rwmhreset-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/1/wikileaks/rwmhreset-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/wikileaks/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/wikileaks/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/wikileaks/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/wikileaks/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/wikileaks/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/wikileaks/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/wikileaks/qrs-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/wikileaks/qrs-wikileaks-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/wikileaks/rwmh-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/wikileaks/rwmh-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/wikileaks/rwmhreset-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/2/wikileaks/rwmhreset-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/wikileaks/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/wikileaks/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/wikileaks/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/wikileaks/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/wikileaks/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/wikileaks/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/wikileaks/qrs-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/wikileaks/qrs-wikileaks-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/wikileaks/rwmh-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/wikileaks/rwmh-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/wikileaks/rwmhreset-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/3/wikileaks/rwmhreset-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/wikileaks/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/wikileaks/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/wikileaks/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/wikileaks/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/wikileaks/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/wikileaks/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/wikileaks/qrs-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/wikileaks/qrs-wikileaks-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/wikileaks/rwmh-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/wikileaks/rwmh-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/wikileaks/rwmhreset-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/4/wikileaks/rwmhreset-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/wikileaks/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/wikileaks/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/wikileaks/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/wikileaks/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/wikileaks/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/wikileaks/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/wikileaks/qrs-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/wikileaks/qrs-wikileaks-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/wikileaks/rwmh-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/wikileaks/rwmh-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/wikileaks/rwmhreset-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/5/wikileaks/rwmhreset-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/wikileaks/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/wikileaks/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/wikileaks/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/wikileaks/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/wikileaks/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/wikileaks/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/wikileaks/qrs-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/wikileaks/qrs-wikileaks-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/wikileaks/rwmh-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/wikileaks/rwmh-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/wikileaks/rwmhreset-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/6/wikileaks/rwmhreset-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/wikileaks/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/wikileaks/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/wikileaks/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/wikileaks/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/wikileaks/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/wikileaks/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/wikileaks/qrs-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/wikileaks/qrs-wikileaks-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/wikileaks/rwmh-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/wikileaks/rwmh-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/wikileaks/rwmhreset-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/7/wikileaks/rwmhreset-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/wikileaks/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/wikileaks/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/wikileaks/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/wikileaks/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/wikileaks/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/wikileaks/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/wikileaks/qrs-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/wikileaks/qrs-wikileaks-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/wikileaks/rwmh-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/wikileaks/rwmh-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/wikileaks/rwmhreset-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/8/wikileaks/rwmhreset-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/wikileaks/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/wikileaks/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/wikileaks/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/wikileaks/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/wikileaks/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/wikileaks/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/wikileaks/qrs-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/wikileaks/qrs-wikileaks-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/wikileaks/rwmh-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/wikileaks/rwmh-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/wikileaks/rwmhreset-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/9/wikileaks/rwmhreset-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/wikileaks/imh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/wikileaks/imh-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/wikileaks/imhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/wikileaks/imhreset-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/wikileaks/rwmh-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/wikileaks/rwmhreset-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/wikileaks/qrs-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/wikileaks/qrs-wikileaks-0.001.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/wikileaks/rwmh-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/wikileaks/rwmh-0.001-wikileaks-0.01.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/wikileaks/rwmhreset-0.001-wikileaks-0.1.pkl"
python score-samples.py --scorer="base" --reset-tokenization --samples="<output-dir>/10k/10/wikileaks/rwmhreset-0.001-wikileaks-0.01.pkl"
python score-samples.py --samples="<output-dir>/10k/1/female_science/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/1/amazing/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/2/female_science/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/2/amazing/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/3/female_science/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/3/amazing/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/4/female_science/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/4/amazing/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/5/female_science/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/5/amazing/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/6/female_science/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/6/amazing/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/7/female_science/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/7/amazing/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/8/female_science/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/8/amazing/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/9/female_science/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/9/amazing/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/10/female_science/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/10/amazing/direct.pkl" --scorer="ebm"
python score-samples.py --samples="<output-dir>/10k/1/female_science/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/1/amazing/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/2/female_science/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/2/amazing/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/3/female_science/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/3/amazing/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/4/female_science/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/4/amazing/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/5/female_science/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/5/amazing/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/6/female_science/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/6/amazing/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/7/female_science/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/7/amazing/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/8/female_science/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/8/amazing/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/9/female_science/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/9/amazing/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/10/female_science/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/10/amazing/direct.pkl" --scorer="proposal"
python score-samples.py --samples="<output-dir>/10k/1/female_science/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/1/amazing/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/2/female_science/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/2/amazing/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/3/female_science/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/3/amazing/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/4/female_science/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/4/amazing/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/5/female_science/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/5/amazing/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/6/female_science/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/6/amazing/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/7/female_science/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/7/amazing/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/8/female_science/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/8/amazing/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/9/female_science/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/9/amazing/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/10/female_science/direct.pkl" --reset-tokenization --scorer="base"
python score-samples.py --samples="<output-dir>/10k/10/amazing/direct.pkl" --reset-tokenization --scorer="base"
