# qrs
# Copyright (c) 2022-present NAVER Corp.
# Creative Commons Attribution-NonCommercial-ShareAlike 4.0 license

sampler:
  args:
    beta: 0.000885635323356837
    truncate: true
  class: RejectionSampler
