# qrs 
# Copyright (c) 2022-present NAVER Corp. 
# Creative Commons Attribution-NonCommercial-ShareAlike 4.0 license

base:
  class: "lm.HFAutoregressiveLM"
  args:
    model_name: "gpt2"
filters:
  - class: "SingleWordFeature"
    args: 
      word: "amazing"
